//
// AudioAttachmentModelWaveform.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif
import Vapor

public struct AudioAttachmentModelWaveform: Content, Hashable {

    public var dataSetLength: Int
    public var highestValue: Int
    public var lowestValue: Int
    public var data: [Int]

    public init(dataSetLength: Int, highestValue: Int, lowestValue: Int, data: [Int]) {
        self.dataSetLength = dataSetLength
        self.highestValue = highestValue
        self.lowestValue = lowestValue
        self.data = data
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case dataSetLength
        case highestValue
        case lowestValue
        case data
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(dataSetLength, forKey: .dataSetLength)
        try container.encode(highestValue, forKey: .highestValue)
        try container.encode(lowestValue, forKey: .lowestValue)
        try container.encode(data, forKey: .data)
    }
}

