//
// AuthLoginV2Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif
import Vapor

public struct AuthLoginV2Response: Content, Hashable {

    public var user: UserModel?
    /** If true, the user has not yet been authenticated, and will need to submit the 2FA token to complete authentication. */
    public var needs2FA: Bool

    public init(user: UserModel? = nil, needs2FA: Bool) {
        self.user = user
        self.needs2FA = needs2FA
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case user
        case needs2FA
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(user, forKey: .user)
        try container.encode(needs2FA, forKey: .needs2FA)
    }
}

