//
// BlogPostModelV3CreatorCategory.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif
import Vapor

public struct BlogPostModelV3CreatorCategory: Content, Hashable {

    public var title: String?

    public init(title: String? = nil) {
        self.title = title
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case title
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(title, forKey: .title)
    }
}

