//
// CdnDeliveryV3MediaBitrateInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif
import Vapor

public struct CdnDeliveryV3MediaBitrateInfo: Content, Hashable {

    public var bitrate: CdnDeliveryV3MediaBitrateInfoBitrate?

    public init(bitrate: CdnDeliveryV3MediaBitrateInfoBitrate? = nil) {
        self.bitrate = bitrate
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case bitrate
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(bitrate, forKey: .bitrate)
    }
}

