//
// CdnDeliveryV2VodResponseResourceData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif
import Vapor

public struct CdnDeliveryV2VodResponseResourceData: Content, Hashable {

    public var qualityLevels: [CdnDeliveryV2QualityLevelModel]
    /** For each `qualityLevel` above, there will be an entry in this map where the property name matches the `qulityLevel[].name` containing a token to apply to the URL. */
    public var qualityLevelParams: [String: CdnDeliveryV2VodResponseResourceDataQualityLevelParamsValue]

    public init(qualityLevels: [CdnDeliveryV2QualityLevelModel], qualityLevelParams: [String: CdnDeliveryV2VodResponseResourceDataQualityLevelParamsValue]) {
        self.qualityLevels = qualityLevels
        self.qualityLevelParams = qualityLevelParams
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case qualityLevels
        case qualityLevelParams
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(qualityLevels, forKey: .qualityLevels)
        try container.encode(qualityLevelParams, forKey: .qualityLevelParams)
    }
}

