//
// CdnDeliveryV2Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif
import Vapor

public enum CdnDeliveryV2Response: Content {
    case typeCdnDeliveryV2DownloadResponse(CdnDeliveryV2DownloadResponse)
    case typeCdnDeliveryV2LivestreamResponse(CdnDeliveryV2LivestreamResponse)
    case typeCdnDeliveryV2VodResponse(CdnDeliveryV2VodResponse)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeCdnDeliveryV2DownloadResponse(let value):
            try container.encode(value)
        case .typeCdnDeliveryV2LivestreamResponse(let value):
            try container.encode(value)
        case .typeCdnDeliveryV2VodResponse(let value):
            try container.encode(value)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(CdnDeliveryV2DownloadResponse.self) {
            self = .typeCdnDeliveryV2DownloadResponse(value)
        } else if let value = try? container.decode(CdnDeliveryV2LivestreamResponse.self) {
            self = .typeCdnDeliveryV2LivestreamResponse(value)
        } else if let value = try? container.decode(CdnDeliveryV2VodResponse.self) {
            self = .typeCdnDeliveryV2VodResponse(value)
        } else {
            throw DecodingError.typeMismatch(Self.Type.self, .init(codingPath: decoder.codingPath, debugDescription: "Unable to decode instance of CdnDeliveryV2Response"))
        }
    }
}

