//
// CdnDeliveryV2LivestreamResponseResource.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif
import Vapor

public struct CdnDeliveryV2LivestreamResponseResource: Content, Hashable {

    /** The path to attach to the `cdn` property above. Replace the items surrounded by curly braces (`{`, `}`) with the appropriate values from the `data` property. */
    public var uri: String
    public var data: CdnDeliveryV2VodResponseResourceDataQualityLevelParamsValue

    public init(uri: String, data: CdnDeliveryV2VodResponseResourceDataQualityLevelParamsValue) {
        self.uri = uri
        self.data = data
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case uri
        case data
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(uri, forKey: .uri)
        try container.encode(data, forKey: .data)
    }
}

