//
// CdnDeliveryV3MetaLive.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif
import Vapor

public struct CdnDeliveryV3MetaLive: Content, Hashable {

    public enum LowLatencyExtension: String, Content, Hashable, CaseIterable {
        case llhls = "llhls"
        case clhls = "clhls"
        case ivshls = "ivshls"
        case lldash = "lldash"
    }
    /** - `llhls`: 🍎-backed low-latency HLS extension. - `clhls`: Community-backed low-latency HLS extension. - `ivshls`: IVS custom low-latency HLS extension. - `lldash`: DASH-IF-backed low-Latency DASH extension. */
    public var lowLatencyExtension: LowLatencyExtension?

    public init(lowLatencyExtension: LowLatencyExtension? = nil) {
        self.lowLatencyExtension = lowLatencyExtension
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case lowLatencyExtension
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(lowLatencyExtension, forKey: .lowLatencyExtension)
    }
}

