//
// CdnDeliveryV3MetaVideoAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif
import Vapor

public struct CdnDeliveryV3MetaVideoAllOf: Content, Hashable {

    /** Maximum count of frames presented per second for the video. */
    public var fps: Double?

    public init(fps: Double? = nil) {
        self.fps = fps
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case fps
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(fps, forKey: .fps)
    }
}

