//
// CdnDeliveryV3MediaBitrateInfoBitrate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif
import Vapor

public struct CdnDeliveryV3MediaBitrateInfoBitrate: Content, Hashable {

    /** Maximum bitrate observed for the data stream. */
    public var maximum: Double?
    /** Average bitrate observed for the data stream. */
    public var average: Double?

    public init(maximum: Double? = nil, average: Double? = nil) {
        self.maximum = maximum
        self.average = average
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case maximum
        case average
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(maximum, forKey: .maximum)
        try container.encodeIfPresent(average, forKey: .average)
    }
}

