//
// CdnDeliveryV2DownloadResponseAllOfResourceData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif
import Vapor

public struct CdnDeliveryV2DownloadResponseAllOfResourceData: Content, Hashable {

    public var qualityLevels: [CdnDeliveryV2QualityLevelModel]
    public var token: String

    public init(qualityLevels: [CdnDeliveryV2QualityLevelModel], token: String) {
        self.qualityLevels = qualityLevels
        self.token = token
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case qualityLevels
        case token
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(qualityLevels, forKey: .qualityLevels)
        try container.encode(token, forKey: .token)
    }
}

