//
// CdnDeliveryV3Meta.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif
import Vapor

/** Metadata information for this variant. Note that most/all child and grandchild properties are not required on purpose. */
public struct CdnDeliveryV3Meta: Content, Hashable {

    public var common: CdnDeliveryV3MetaCommon?
    public var video: CdnDeliveryV3MetaVideo?
    public var audio: CdnDeliveryV3MetaAudio?
    public var image: CdnDeliveryV3MetaImage?
    public var live: CdnDeliveryV3MetaLive?

    public init(common: CdnDeliveryV3MetaCommon? = nil, video: CdnDeliveryV3MetaVideo? = nil, audio: CdnDeliveryV3MetaAudio? = nil, image: CdnDeliveryV3MetaImage? = nil, live: CdnDeliveryV3MetaLive? = nil) {
        self.common = common
        self.video = video
        self.audio = audio
        self.image = image
        self.live = live
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case common
        case video
        case audio
        case image
        case live
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(common, forKey: .common)
        try container.encodeIfPresent(video, forKey: .video)
        try container.encodeIfPresent(audio, forKey: .audio)
        try container.encodeIfPresent(image, forKey: .image)
        try container.encodeIfPresent(live, forKey: .live)
    }
}

