//
// CdnDeliveryV3MetaCommon.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif
import Vapor

public struct CdnDeliveryV3MetaCommon: Content, Hashable {

    /** Size of the corresponding media file, measured in bytes. */
    public var size: Double?
    public var access: CdnDeliveryV3MetaCommonAccess?

    public init(size: Double? = nil, access: CdnDeliveryV3MetaCommonAccess? = nil) {
        self.size = size
        self.access = access
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case size
        case access
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(size, forKey: .size)
        try container.encodeIfPresent(access, forKey: .access)
    }
}

