//
// CdnDeliveryV3Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif
import Vapor

public struct CdnDeliveryV3Response: Content, Hashable {

    /** `groups` may consist of zero or more elements. */
    public var groups: [CdnDeliveryV3Group]

    public init(groups: [CdnDeliveryV3Group]) {
        self.groups = groups
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case groups
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(groups, forKey: .groups)
    }
}

