//
// ChildImageModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif
import Vapor

public struct ChildImageModel: Content, Hashable {

    public var width: Int
    public var height: Int
    public var path: String

    public init(width: Int, height: Int, path: String) {
        self.width = width
        self.height = height
        self.path = path
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case width
        case height
        case path
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(width, forKey: .width)
        try container.encode(height, forKey: .height)
        try container.encode(path, forKey: .path)
    }
}

