//
// CommentModelInteractionCounts.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif
import Vapor

public struct CommentModelInteractionCounts: Content, Hashable {

    public var like: Int?
    public var dislike: Int?

    public init(like: Int? = nil, dislike: Int? = nil) {
        self.like = like
        self.dislike = dislike
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case like
        case dislike
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(like, forKey: .like)
        try container.encodeIfPresent(dislike, forKey: .dislike)
    }
}

