//
// CommentLikeV3PostRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif
import Vapor

public struct CommentLikeV3PostRequest: Content, Hashable {

    /** The GUID of the comment being liked. */
    public var comment: String
    /** The GUID of the post the comment is on. */
    public var blogPost: String

    public init(comment: String, blogPost: String) {
        self.comment = comment
        self.blogPost = blogPost
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case comment
        case blogPost
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(comment, forKey: .comment)
        try container.encode(blogPost, forKey: .blogPost)
    }
}

