//
// ConnectedAccountModelConnectedAccountData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif
import Vapor

public struct ConnectedAccountModelConnectedAccountData: Content, Hashable {

    public var canJoinGuilds: Bool

    public init(canJoinGuilds: Bool) {
        self.canJoinGuilds = canJoinGuilds
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case canJoinGuilds
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(canJoinGuilds, forKey: .canJoinGuilds)
    }
}

