//
// ConnectedAccountModelConnectedAccount.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif
import Vapor

public struct ConnectedAccountModelConnectedAccount: Content, Hashable {

    public var id: String
    public var remoteUserId: String
    public var remoteUserName: String
    public var data: ConnectedAccountModelConnectedAccountData

    public init(id: String, remoteUserId: String, remoteUserName: String, data: ConnectedAccountModelConnectedAccountData) {
        self.id = id
        self.remoteUserId = remoteUserId
        self.remoteUserName = remoteUserName
        self.data = data
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case remoteUserId
        case remoteUserName
        case data
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(remoteUserId, forKey: .remoteUserId)
        try container.encode(remoteUserName, forKey: .remoteUserName)
        try container.encode(data, forKey: .data)
    }
}

