//
// ContentCreatorListV3Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif
import Vapor

public struct ContentCreatorListV3Response: Content, Hashable {

    public var blogPosts: [BlogPostModelV3]
    /** Information about paging: what the last ID retrieve is and if more posts can be retrieved afterward for subsequent requests. */
    public var lastElements: [ContentCreatorListLastItems]

    public init(blogPosts: [BlogPostModelV3], lastElements: [ContentCreatorListLastItems]) {
        self.blogPosts = blogPosts
        self.lastElements = lastElements
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case blogPosts
        case lastElements
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(blogPosts, forKey: .blogPosts)
        try container.encode(lastElements, forKey: .lastElements)
    }
}

