//
// ContentCreatorListLastItems.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif
import Vapor

public struct ContentCreatorListLastItems: Content, Hashable {

    public var creatorId: String
    /** This may be returned as `null` if no blog posts for this creator appeared yet on this page of blog posts. However, Floatplane will complain if this is sent with a `null` value. */
    public var blogPostId: String?
    public var moreFetchable: Bool

    public init(creatorId: String, blogPostId: String?, moreFetchable: Bool) {
        self.creatorId = creatorId
        self.blogPostId = blogPostId
        self.moreFetchable = moreFetchable
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case creatorId
        case blogPostId
        case moreFetchable
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(creatorId, forKey: .creatorId)
        try container.encode(blogPostId, forKey: .blogPostId)
        try container.encode(moreFetchable, forKey: .moreFetchable)
    }
}

