//
// CreatorModelV3OwnerOneOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif
import Vapor

public struct CreatorModelV3OwnerOneOf: Content, Hashable {

    public var id: String?
    public var username: String?

    public init(id: String? = nil, username: String? = nil) {
        self.id = id
        self.username = username
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case username
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(username, forKey: .username)
    }
}

