//
// CreatorModelV2ExtendedAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif
import Vapor

public struct CreatorModelV2ExtendedAllOf: Content, Hashable {

    public var socialLinks: [String: String]
    public var discordServers: [DiscordServerModel]

    public init(socialLinks: [String: String], discordServers: [DiscordServerModel]) {
        self.socialLinks = socialLinks
        self.discordServers = discordServers
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case socialLinks
        case discordServers
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(socialLinks, forKey: .socialLinks)
        try container.encode(discordServers, forKey: .discordServers)
    }
}

