//
// CreatorModelV3Owner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif
import Vapor

public enum CreatorModelV3Owner: Content, Hashable {
    case typeCreatorModelV3OwnerOneOf(CreatorModelV3OwnerOneOf)
    case typeString(String)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeCreatorModelV3OwnerOneOf(let value):
            try container.encode(value)
        case .typeString(let value):
            try container.encode(value)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(CreatorModelV3OwnerOneOf.self) {
            self = .typeCreatorModelV3OwnerOneOf(value)
        } else if let value = try? container.decode(String.self) {
            self = .typeString(value)
        } else {
            throw DecodingError.typeMismatch(Self.Type.self, .init(codingPath: decoder.codingPath, debugDescription: "Unable to decode instance of CreatorModelV3Owner"))
        }
    }
}

