//
// EdgesModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif
import Vapor

public struct EdgesModel: Content, Hashable {

    public var edges: [EdgeModel]
    public var client: [String: AnyCodable]

    public init(edges: [EdgeModel], client: [String: AnyCodable]) {
        self.edges = edges
        self.client = client
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case edges
        case client
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(edges, forKey: .edges)
        try container.encode(client, forKey: .client)
    }
}

