//
// ErrorModelErrorsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif
import Vapor

public struct ErrorModelErrorsInner: Content, Hashable {

    public var id: String
    public var name: String
    /** May be undefined. */
    public var message: String?
    /** May be undefined. */
    public var data: [String: AnyCodable]?

    public init(id: String, name: String, message: String? = nil, data: [String: AnyCodable]? = nil) {
        self.id = id
        self.name = name
        self.message = message
        self.data = data
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case message
        case data
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(message, forKey: .message)
        try container.encodeIfPresent(data, forKey: .data)
    }
}

