//
// FaqSectionModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif
import Vapor

public struct FaqSectionModel: Content, Hashable {

    public enum Status: String, Content, Hashable, CaseIterable {
        case _public = "public"
    }
    public var faqs: [FaqSectionModelFaqs]
    public var createdAt: Date
    public var updatedAt: Date
    public var id: String
    public var name: String
    public var description: String
    public var status: Status
    public var order: Double

    public init(faqs: [FaqSectionModelFaqs], createdAt: Date, updatedAt: Date, id: String, name: String, description: String, status: Status, order: Double) {
        self.faqs = faqs
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.id = id
        self.name = name
        self.description = description
        self.status = status
        self.order = order
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case faqs
        case createdAt
        case updatedAt
        case id
        case name
        case description
        case status
        case order
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(faqs, forKey: .faqs)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(updatedAt, forKey: .updatedAt)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encode(description, forKey: .description)
        try container.encode(status, forKey: .status)
        try container.encode(order, forKey: .order)
    }
}

