//
// GetCaptchaInfoResponseV2Variants.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif
import Vapor

public struct GetCaptchaInfoResponseV2Variants: Content, Hashable {

    public var android: GetCaptchaInfoResponseV2VariantsAndroid
    public var checkbox: GetCaptchaInfoResponseV2VariantsAndroid
    public var invisible: GetCaptchaInfoResponseV2VariantsAndroid

    public init(android: GetCaptchaInfoResponseV2VariantsAndroid, checkbox: GetCaptchaInfoResponseV2VariantsAndroid, invisible: GetCaptchaInfoResponseV2VariantsAndroid) {
        self.android = android
        self.checkbox = checkbox
        self.invisible = invisible
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case android
        case checkbox
        case invisible
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(android, forKey: .android)
        try container.encode(checkbox, forKey: .checkbox)
        try container.encode(invisible, forKey: .invisible)
    }
}

