//
// GetCaptchaInfoResponseV3Variants.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif
import Vapor

public struct GetCaptchaInfoResponseV3Variants: Content, Hashable {

    public var invisible: GetCaptchaInfoResponseV2VariantsAndroid

    public init(invisible: GetCaptchaInfoResponseV2VariantsAndroid) {
        self.invisible = invisible
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case invisible
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(invisible, forKey: .invisible)
    }
}

