//
// GetCaptchaInfoResponseV2VariantsAndroid.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif
import Vapor

public struct GetCaptchaInfoResponseV2VariantsAndroid: Content, Hashable {

    public var siteKey: String

    public init(siteKey: String) {
        self.siteKey = siteKey
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case siteKey
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(siteKey, forKey: .siteKey)
    }
}

