//
// GetCaptchaInfoResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif
import Vapor

public struct GetCaptchaInfoResponse: Content, Hashable {

    public var v2: GetCaptchaInfoResponseV2
    public var v3: GetCaptchaInfoResponseV3

    public init(v2: GetCaptchaInfoResponseV2, v3: GetCaptchaInfoResponseV3) {
        self.v2 = v2
        self.v3 = v3
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case v2
        case v3
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(v2, forKey: .v2)
        try container.encode(v3, forKey: .v3)
    }
}

