//
// GetProgressRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif
import Vapor

/**  */
public struct GetProgressRequest: Content, Hashable {

    public enum ContentType: String, Content, Hashable, CaseIterable {
        case blogpost = "blogPost"
    }
    /** The identifiers of the blog posts from which progress should be retrieved. */
    public var ids: [String]
    /** The type of the corresponding identifiers. The only value currently is `blogPost`. */
    public var contentType: ContentType

    public init(ids: [String], contentType: ContentType) {
        self.ids = ids
        self.contentType = contentType
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case ids
        case contentType
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(ids, forKey: .ids)
        try container.encode(contentType, forKey: .contentType)
    }
}

