//
// ImageFileModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif
import Vapor

public struct ImageFileModel: Content, Hashable {

    public var path: String
    public var width: Int
    public var height: Int
    public var size: Int

    public init(path: String, width: Int, height: Int, size: Int) {
        self.path = path
        self.width = width
        self.height = height
        self.size = size
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case path
        case width
        case height
        case size
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(path, forKey: .path)
        try container.encode(width, forKey: .width)
        try container.encode(height, forKey: .height)
        try container.encode(size, forKey: .size)
    }
}

