//
// ImageModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif
import Vapor

public struct ImageModel: Content, Hashable {

    public var width: Int
    public var height: Int
    public var path: String
    public var size: Int?
    public var childImages: [ChildImageModel]?

    public init(width: Int, height: Int, path: String, size: Int? = nil, childImages: [ChildImageModel]? = nil) {
        self.width = width
        self.height = height
        self.path = path
        self.size = size
        self.childImages = childImages
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case width
        case height
        case path
        case size
        case childImages
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(width, forKey: .width)
        try container.encode(height, forKey: .height)
        try container.encode(path, forKey: .path)
        try container.encodeIfPresent(size, forKey: .size)
        try container.encodeIfPresent(childImages, forKey: .childImages)
    }
}

