//
// PaymentInvoiceListV2ResponsePlanCreator.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif
import Vapor

public struct PaymentInvoiceListV2ResponsePlanCreator: Content, Hashable {

    public var id: String
    public var title: String
    public var urlname: String
    public var icon: ImageModel

    public init(id: String, title: String, urlname: String, icon: ImageModel) {
        self.id = id
        self.title = title
        self.urlname = urlname
        self.icon = icon
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case title
        case urlname
        case icon
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(title, forKey: .title)
        try container.encode(urlname, forKey: .urlname)
        try container.encode(icon, forKey: .icon)
    }
}

