//
// PaymentMethodModelCard.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif
import Vapor

public struct PaymentMethodModelCard: Content, Hashable {

    public var brand: String
    public var last4: String
    public var expMonth: Int
    public var expYear: Int
    public var name: String

    public init(brand: String, last4: String, expMonth: Int, expYear: Int, name: String) {
        self.brand = brand
        self.last4 = last4
        self.expMonth = expMonth
        self.expYear = expYear
        self.name = name
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case brand
        case last4
        case expMonth = "exp_month"
        case expYear = "exp_year"
        case name
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(brand, forKey: .brand)
        try container.encode(last4, forKey: .last4)
        try container.encode(expMonth, forKey: .expMonth)
        try container.encode(expYear, forKey: .expYear)
        try container.encode(name, forKey: .name)
    }
}

