//
// PaymentInvoiceListV2ResponsePlan.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif
import Vapor

public struct PaymentInvoiceListV2ResponsePlan: Content, Hashable {

    public var id: String
    public var title: String
    public var creator: PaymentInvoiceListV2ResponsePlanCreator

    public init(id: String, title: String, creator: PaymentInvoiceListV2ResponsePlanCreator) {
        self.id = id
        self.title = title
        self.creator = creator
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case title
        case creator
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(title, forKey: .title)
        try container.encode(creator, forKey: .creator)
    }
}

