//
// PaymentMethodModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif
import Vapor

public struct PaymentMethodModel: Content, Hashable {

    public var id: Int
    public var paymentProcessor: Int
    public var _default: Bool
    public var card: PaymentMethodModelCard

    public init(id: Int, paymentProcessor: Int, _default: Bool, card: PaymentMethodModelCard) {
        self.id = id
        self.paymentProcessor = paymentProcessor
        self._default = _default
        self.card = card
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case paymentProcessor = "payment_processor"
        case _default = "default"
        case card
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(paymentProcessor, forKey: .paymentProcessor)
        try container.encode(_default, forKey: ._default)
        try container.encode(card, forKey: .card)
    }
}

