//
// PlanInfoV2Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif
import Vapor

public struct PlanInfoV2Response: Content, Hashable {

    /** The total number of subscribers for this creator. */
    public var totalSubscriberCount: Int
    /** The total amount of monthly income for this creator. This field tends to always be $0 for regular users. */
    public var totalIncome: String?
    public var plans: [PlanInfoV2ResponsePlansInner]

    public init(totalSubscriberCount: Int, totalIncome: String?, plans: [PlanInfoV2ResponsePlansInner]) {
        self.totalSubscriberCount = totalSubscriberCount
        self.totalIncome = totalIncome
        self.plans = plans
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case totalSubscriberCount
        case totalIncome
        case plans
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(totalSubscriberCount, forKey: .totalSubscriberCount)
        try container.encode(totalIncome, forKey: .totalIncome)
        try container.encode(plans, forKey: .plans)
    }
}

