//
// UserInfoV2ResponseUsersInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif
import Vapor

public struct UserInfoV2ResponseUsersInner: Content, Hashable {

    public var id: String
    public var user: UserInfoV2ResponseUsersInnerUser

    public init(id: String, user: UserInfoV2ResponseUsersInnerUser) {
        self.id = id
        self.user = user
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case user
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(user, forKey: .user)
    }
}

