//
// UserSelfModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif
import Vapor

public struct UserSelfModel: Content, Hashable {

    public var id: String
    public var username: String
    public var profileImage: ImageModel
    public var email: String
    public var displayName: String

    public init(id: String, username: String, profileImage: ImageModel, email: String, displayName: String) {
        self.id = id
        self.username = username
        self.profileImage = profileImage
        self.email = email
        self.displayName = displayName
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case username
        case profileImage
        case email
        case displayName
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(username, forKey: .username)
        try container.encode(profileImage, forKey: .profileImage)
        try container.encode(email, forKey: .email)
        try container.encode(displayName, forKey: .displayName)
    }
}

