//
// UserInfoV2ResponseUsersInnerUser.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif
import Vapor

public enum UserInfoV2ResponseUsersInnerUser: Content, Hashable {
    case typeUserModel(UserModel)
    case typeUserSelfModel(UserSelfModel)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeUserModel(let value):
            try container.encode(value)
        case .typeUserSelfModel(let value):
            try container.encode(value)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(UserModel.self) {
            self = .typeUserModel(value)
        } else if let value = try? container.decode(UserSelfModel.self) {
            self = .typeUserSelfModel(value)
        } else {
            throw DecodingError.typeMismatch(Self.Type.self, .init(codingPath: decoder.codingPath, debugDescription: "Unable to decode instance of UserInfoV2ResponseUsersInnerUser"))
        }
    }
}

