//
// UserLinksV3ResponseValueType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif
import Vapor

public struct UserLinksV3ResponseValueType: Content, Hashable {

    /** The code name of this link type. */
    public var name: String
    /** The display-friendly name of this link type. */
    public var displayName: String
    /** The hostname that should be a part of the URL. */
    public var hostName: String

    public init(name: String, displayName: String, hostName: String) {
        self.name = name
        self.displayName = displayName
        self.hostName = hostName
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case displayName
        case hostName
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(displayName, forKey: .displayName)
        try container.encode(hostName, forKey: .hostName)
    }
}

