//
// VotePollRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif
import Vapor

public struct VotePollRequest: Content, Hashable {

    /** The id of the poll to vote on. */
    public var pollId: String
    /** The index of the options of the poll for which to vote. This should not be outside the bounds of the poll options. */
    public var optionIndex: Int

    public init(pollId: String, optionIndex: Int) {
        self.pollId = pollId
        self.optionIndex = optionIndex
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case pollId
        case optionIndex
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(pollId, forKey: .pollId)
        try container.encode(optionIndex, forKey: .optionIndex)
    }
}

