name: Build

on:
  push:
  pull_request:

jobs:
  tvOS:
    name: tvOS
    runs-on: macOS-13
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: xcodebuild -project Wasserflug-tvOS.xcodeproj -scheme Wasserflug-tvOS -destination "generic/platform=tvOS Simulator"
